---
name: "CI for PRs"
on:
  pull_request:
    branches:
      - master
jobs:
  lint:
    name: Lint
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout the PR
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install dependencies
        run: pip3 install -r ci.txt
      - name: Run linting
        run: invoke lint
  build:
    name: Build the Docker images
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout the PR
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install dependencies
        run: pip3 install -r ci.txt
      - name: Build the Docker images
        run: invoke build
