---
name: "CI for commits"
on:
  push:
    branches:
      - main
jobs:
  lint:
    name: Lint
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip3 install -r ci.txt && echo "/home/runner/.local/bin" >> "${GITHUB_PATH}"
      - name: Run linting
        run: invoke lint
  build:
    name: Build, test, and push the Docker images
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip3 install -r ci.txt && echo "/home/runner/.local/bin" >> "${GITHUB_PATH}"
      - name: Build the Docker images
        run: invoke build
      - name: Test the Docker images
        run: invoke test
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish the Docker images
        run: invoke publish
