---
name: "CI for PRs"
on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Lint
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout the PR
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install dependencies
        run: pip3 install -r ci.txt && echo "/home/runner/.local/bin" >> "${GITHUB_PATH}"
      - name: Run linting
        run: invoke lint
  build:
    name: Build and test the Docker images
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout the PR
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install dependencies
        run: pip3 install -r ci.txt && echo "/home/runner/.local/bin" >> "${GITHUB_PATH}"
      - name: Build the Docker images
        run: invoke build
      - name: Test the Docker images
        run: invoke test
