---
name: "Update"

on:
  schedule:
    - cron: '17 4 * * 1,4'

jobs:
  update:
    name: Update
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install the dependencies
        run: |
          python -m pip install --upgrade pipenv
          pipenv install --dev
      - name: Update the repository
        run: pipenv run invoke update
      - name: Create or update a pull request
        uses: peter-evans/create-pull-request@v4
        with:
          title: Automated update to primary components
          commit-message: Automated update to primary components
          committer: Seiso Automation <automation@seisollc.com>
          delete-branch: true
          signoff: true
